//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class project {
    
    private projectProgram[] programField;
    
    private projectImage[] imageField;
    
    private projectSprite[] spriteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("program")]
    public projectProgram[] program {
        get {
            return this.programField;
        }
        set {
            this.programField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image")]
    public projectImage[] image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sprite")]
    public projectSprite[] sprite {
        get {
            return this.spriteField;
        }
        set {
            this.spriteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class projectProgram {
    
    private string fileField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("file")]
    public string Filename {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }

	public bool DirtyFlag { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class projectImage {
    
    private string fileField;
    
    /// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute("file")]
	public string Filename {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }

	public bool DirtyFlag { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class projectSprite {

	private string fileField;
    
    /// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute("file")]
	public string Filename {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }

	public bool DirtyFlag { get; set; }
}
